all:
  vars:
    control_plane_endpoint: 192.168.1.100
    load_balancer_ip_pool:
      - 192.168.1.224/27
metal:
  children:
    masters:
      hosts:
        metal0: {ansible_host: 192.168.0.20, mac: 'f8:b1:56:d8:3b:4b', disk: sda, network_interface: enp0s25, nebula_name: server1, nebula_ip: 192.168.100.2, lighthouse: false}
