app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: quay.io/redlib/redlib
            tag: sha-d9e7681
  service:
    main:
      ports:
        http:
          port: 8080
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - host: &host redlib.iamawak.co
          paths:
            - path: /
              pathType: Prefix
              service:
                name: main
                port: http
      tls:
        - hosts:
            - *host
          secretName: redib-tls-certificate
