drawio:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: "homelab-tunnel.iamawak.co"
      external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    hosts:
      - host: &host drawio.iamawak.co
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: drawio-tls-certificate
        hosts:
          - *host
